### ISSUE TITLE
Traced functions overriding non-traced functions of same name/arity

### ISSUE THREAD

**Issue by dabarrell** [newrelic/elixir_agent#115] opened 2019-05-12 06:45 UTC
**Describe the bug**
I believe I've some undocumented behaviour of the New Relic agent, which may be a bug. When you have multiple functions with the same name + arity but different guards etc and apply a `@trace` to only one of them, the others seem to be ignored.

For example:
```elixir
defmodule Example do
  use NewRelic.Tracer

  def random(value) when value == [], do: nil

  @trace :random
  def random(value), do: <something you really don't want to do if value is []>
end
```

In the above, all calls to `random/1` would go to the second definition, regardless of `value`. I can't find any documentation of this behaviour and haven't yet dug into why it happens exactly (I assume NR is replacing the function in the module attributes with it's own macro-ed function and in doing so removes the existing ones). Adding a trace to both functions prevents this.

**Environment**
* Elixir & Erlang version (`elixir -v`): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Agent version (`mix deps | grep new_relic_agent`): 1.9.7

**Comment by binaryseed** [comment] 2019-05-13 19:56
Hello!

The annotations don't need to be on _all_ the functions but they do need to be on the _first_. I'll see if I can add a warning that detects this situation...

**Comment by binaryseed** [comment] 2019-05-13 21:51
I tried out your example, but I can't reproduce this behavior... If you can get it to reproduce, would you mind submitting a test case via this test: 

* https://github.com/newrelic/elixir_agent/blob/master/test/tracer_test.exs

**Comment by binaryseed** [comment] 2019-05-27 03:50
Closing since I can't repro.. please re-open if you can provide a reproduction case.

**Closed by binaryseed** 2019-05-27 03:50 UTC
